name: CI

# commment on 30.07.2022 because github wants to deacivate my schedule

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 1 * * *'  # every night at 1 (UTC)

jobs:
  build:
    runs-on: ubuntu-latest
    defaults: 
      run:
        shell: bash
        working-directory: ./maigrueen

    steps:
      - uses: actions/checkout@v3
      
      - id: 'auth'
        name: 'Authenticate to Google Cloud for Dashboard App'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: ${{ secrets.GOOGLE_API }}
          
      - name: Build Go for Dashboard App
        uses: actions/setup-go@v3.1.0
        with: 
          go-version-file: './go.mod'
      - name: Install dependencies
        run: |
          go version
          go get -u golang.org/x/lint/golint
      - name: Run build for Dashboard
        working-directory: Dashboard
        run: go run .
      - name: Build API
        working-directory: AffirmationsAPI
        run: go build .
      
      - name: Build Node.js for maigrueen Website
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'
      - run: npm install
      - run: npm run build --if-present

      - name: FTP Prod Deploy
        uses: SamKirkland/FTP-Deploy-Action@4.1.0
        with:
          server: www103.your-server.de
          username: maigru
          password: ${{ secrets.FTP_HETZNER }}
          server-dir: /home/public_html/maigrueen.dev/
          protocol: ftp
          port: 21
