# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  schedule:
    - cron: '0 3 * * *'  # every night at 3
 # pull_request:
  #  branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  #workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    defaults: 
      run:
        shell: bash
        working-directory: ./maigrueen

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'
      - run: npm install
      - run: npm run build --if-present
      
      - name: Setup Go environment
        uses: actions/setup-go@v3.1.0
        with: 
          go-version-file: './go.mod'
      - name: Install dependencies
        run: |
          go version
          go get -u golang.org/x/lint/golint
      - name: Run build
        working-directory: Dashboard
        run: go build /home/runner/work/maigrueen/maigrueen.de/Dashboard/backend.go
      - name: Run vet & lint
        run: |
          go vet .
          golint .

      - name: FTP Prod Deploy
        # You may pin to the exact commit or the version.
        # uses: SamKirkland/FTP-Deploy-Action@65c6a8f943bbf04faf9b59520a103318b418952e
        uses: SamKirkland/FTP-Deploy-Action@4.1.0
        with:
          # ftp server
          server: server45.webgo24.de
          # ftp username
          username: web6
          # ftp password
          password: ${{ secrets.PROD_FTP_PASSWORD }}
          # Path to upload to on the server. Must end with trailing slash /
          server-dir: /home/www/maigrueen.de/
