name: CI

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 3 * * *'  # every night at 3

jobs:
  build:
    runs-on: ubuntu-latest
    defaults: 
      run:
        shell: bash
        working-directory: ./maigrueen

    steps:
      - uses: actions/checkout@v3
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            maigrueen:
              - 'maigrueen/**'
            dashboard:
              - 'Dashboard/**'
      
      - id: 'auth'
        name: 'Authenticate to Google Cloud for Dashboard App'
        if: steps.filter.outputs.dashboard == 'true'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: ${{ secrets.GOOGLE_API }}
      
      - name: Build Node.js for maigrueen Website
        if: steps.filter.outputs.maigrueen == 'true'
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'
      - run: npm install
      - run: npm run build --if-present
      
      - name: Build Go for Dashboard App
        if: steps.filter.outputs.dashboard == 'true'
        uses: actions/setup-go@v3.1.0
        with: 
          go-version-file: './go.mod'
      - name: Install dependencies
        run: |
          go version
          go get -u golang.org/x/lint/golint
      - name: Run build
        working-directory: Dashboard
        run: go run .

      - name: FTP Prod Deploy
        uses: SamKirkland/FTP-Deploy-Action@4.1.0
        with:
          server: server45.webgo24.de
          username: web6
          password: ${{ secrets.PROD_FTP_PASSWORD }}
          server-dir: /home/www/maigrueen.de/
